//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Rearth.UsuariosServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuariosSoap", Namespace="http://tempuri.org/")]
    public partial class Usuarios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaSOAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaIdSOAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRESTOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaIdRESTOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditarRolOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarRolOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Usuarios() {
            this.Url = global::Rearth.Properties.Settings.Default.Rearth_net_azurewebsites_rearthserv20211119182633_Usuarios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VersionCompletedEventHandler VersionCompleted;
        
        /// <remarks/>
        public event ConsultaSOAPCompletedEventHandler ConsultaSOAPCompleted;
        
        /// <remarks/>
        public event ConsultaIdSOAPCompletedEventHandler ConsultaIdSOAPCompleted;
        
        /// <remarks/>
        public event ConsultaRESTCompletedEventHandler ConsultaRESTCompleted;
        
        /// <remarks/>
        public event ConsultaIdRESTCompletedEventHandler ConsultaIdRESTCompleted;
        
        /// <remarks/>
        public event LogueoCompletedEventHandler LogueoCompleted;
        
        /// <remarks/>
        public event AgregarCompletedEventHandler AgregarCompleted;
        
        /// <remarks/>
        public event AgregarRolCompletedEventHandler AgregarRolCompleted;
        
        /// <remarks/>
        public event EditarCompletedEventHandler EditarCompleted;
        
        /// <remarks/>
        public event EditarRolCompletedEventHandler EditarRolCompleted;
        
        /// <remarks/>
        public event EliminarCompletedEventHandler EliminarCompleted;
        
        /// <remarks/>
        public event EliminarRolCompletedEventHandler EliminarRolCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Version", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Version() {
            object[] results = this.Invoke("Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VersionAsync() {
            this.VersionAsync(null);
        }
        
        /// <remarks/>
        public void VersionAsync(object userState) {
            if ((this.VersionOperationCompleted == null)) {
                this.VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVersionOperationCompleted);
            }
            this.InvokeAsync("Version", new object[0], this.VersionOperationCompleted, userState);
        }
        
        private void OnVersionOperationCompleted(object arg) {
            if ((this.VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VersionCompleted(this, new VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaSOAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista ConsultaSOAP() {
            object[] results = this.Invoke("ConsultaSOAP", new object[0]);
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaSOAPAsync() {
            this.ConsultaSOAPAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaSOAPAsync(object userState) {
            if ((this.ConsultaSOAPOperationCompleted == null)) {
                this.ConsultaSOAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaSOAPOperationCompleted);
            }
            this.InvokeAsync("ConsultaSOAP", new object[0], this.ConsultaSOAPOperationCompleted, userState);
        }
        
        private void OnConsultaSOAPOperationCompleted(object arg) {
            if ((this.ConsultaSOAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaSOAPCompleted(this, new ConsultaSOAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaIdSOAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista ConsultaIdSOAP(string Id) {
            object[] results = this.Invoke("ConsultaIdSOAP", new object[] {
                        Id});
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaIdSOAPAsync(string Id) {
            this.ConsultaIdSOAPAsync(Id, null);
        }
        
        /// <remarks/>
        public void ConsultaIdSOAPAsync(string Id, object userState) {
            if ((this.ConsultaIdSOAPOperationCompleted == null)) {
                this.ConsultaIdSOAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaIdSOAPOperationCompleted);
            }
            this.InvokeAsync("ConsultaIdSOAP", new object[] {
                        Id}, this.ConsultaIdSOAPOperationCompleted, userState);
        }
        
        private void OnConsultaIdSOAPOperationCompleted(object arg) {
            if ((this.ConsultaIdSOAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaIdSOAPCompleted(this, new ConsultaIdSOAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaREST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConsultaREST() {
            this.Invoke("ConsultaREST", new object[0]);
        }
        
        /// <remarks/>
        public void ConsultaRESTAsync() {
            this.ConsultaRESTAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaRESTAsync(object userState) {
            if ((this.ConsultaRESTOperationCompleted == null)) {
                this.ConsultaRESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRESTOperationCompleted);
            }
            this.InvokeAsync("ConsultaREST", new object[0], this.ConsultaRESTOperationCompleted, userState);
        }
        
        private void OnConsultaRESTOperationCompleted(object arg) {
            if ((this.ConsultaRESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRESTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaIdREST", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ConsultaIdREST(string Id) {
            this.Invoke("ConsultaIdREST", new object[] {
                        Id});
        }
        
        /// <remarks/>
        public void ConsultaIdRESTAsync(string Id) {
            this.ConsultaIdRESTAsync(Id, null);
        }
        
        /// <remarks/>
        public void ConsultaIdRESTAsync(string Id, object userState) {
            if ((this.ConsultaIdRESTOperationCompleted == null)) {
                this.ConsultaIdRESTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaIdRESTOperationCompleted);
            }
            this.InvokeAsync("ConsultaIdREST", new object[] {
                        Id}, this.ConsultaIdRESTOperationCompleted, userState);
        }
        
        private void OnConsultaIdRESTOperationCompleted(object arg) {
            if ((this.ConsultaIdRESTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaIdRESTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logueo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista Logueo(string Correo, string Clave) {
            object[] results = this.Invoke("Logueo", new object[] {
                        Correo,
                        Clave});
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoAsync(string Correo, string Clave) {
            this.LogueoAsync(Correo, Clave, null);
        }
        
        /// <remarks/>
        public void LogueoAsync(string Correo, string Clave, object userState) {
            if ((this.LogueoOperationCompleted == null)) {
                this.LogueoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoOperationCompleted);
            }
            this.InvokeAsync("Logueo", new object[] {
                        Correo,
                        Clave}, this.LogueoOperationCompleted, userState);
        }
        
        private void OnLogueoOperationCompleted(object arg) {
            if ((this.LogueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoCompleted(this, new LogueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Agregar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista Agregar(Modelo Objeto, string Token) {
            object[] results = this.Invoke("Agregar", new object[] {
                        Objeto,
                        Token});
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarAsync(Modelo Objeto, string Token) {
            this.AgregarAsync(Objeto, Token, null);
        }
        
        /// <remarks/>
        public void AgregarAsync(Modelo Objeto, string Token, object userState) {
            if ((this.AgregarOperationCompleted == null)) {
                this.AgregarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarOperationCompleted);
            }
            this.InvokeAsync("Agregar", new object[] {
                        Objeto,
                        Token}, this.AgregarOperationCompleted, userState);
        }
        
        private void OnAgregarOperationCompleted(object arg) {
            if ((this.AgregarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCompleted(this, new AgregarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaRol AgregarRol(ModeloRol Objeto, string Token) {
            object[] results = this.Invoke("AgregarRol", new object[] {
                        Objeto,
                        Token});
            return ((ListaRol)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarRolAsync(ModeloRol Objeto, string Token) {
            this.AgregarRolAsync(Objeto, Token, null);
        }
        
        /// <remarks/>
        public void AgregarRolAsync(ModeloRol Objeto, string Token, object userState) {
            if ((this.AgregarRolOperationCompleted == null)) {
                this.AgregarRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarRolOperationCompleted);
            }
            this.InvokeAsync("AgregarRol", new object[] {
                        Objeto,
                        Token}, this.AgregarRolOperationCompleted, userState);
        }
        
        private void OnAgregarRolOperationCompleted(object arg) {
            if ((this.AgregarRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarRolCompleted(this, new AgregarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Editar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista Editar(Modelo Objeto, string Token) {
            object[] results = this.Invoke("Editar", new object[] {
                        Objeto,
                        Token});
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void EditarAsync(Modelo Objeto, string Token) {
            this.EditarAsync(Objeto, Token, null);
        }
        
        /// <remarks/>
        public void EditarAsync(Modelo Objeto, string Token, object userState) {
            if ((this.EditarOperationCompleted == null)) {
                this.EditarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarOperationCompleted);
            }
            this.InvokeAsync("Editar", new object[] {
                        Objeto,
                        Token}, this.EditarOperationCompleted, userState);
        }
        
        private void OnEditarOperationCompleted(object arg) {
            if ((this.EditarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarCompleted(this, new EditarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditarRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaRol EditarRol(ModeloRol Objeto, string Token) {
            object[] results = this.Invoke("EditarRol", new object[] {
                        Objeto,
                        Token});
            return ((ListaRol)(results[0]));
        }
        
        /// <remarks/>
        public void EditarRolAsync(ModeloRol Objeto, string Token) {
            this.EditarRolAsync(Objeto, Token, null);
        }
        
        /// <remarks/>
        public void EditarRolAsync(ModeloRol Objeto, string Token, object userState) {
            if ((this.EditarRolOperationCompleted == null)) {
                this.EditarRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditarRolOperationCompleted);
            }
            this.InvokeAsync("EditarRol", new object[] {
                        Objeto,
                        Token}, this.EditarRolOperationCompleted, userState);
        }
        
        private void OnEditarRolOperationCompleted(object arg) {
            if ((this.EditarRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditarRolCompleted(this, new EditarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Lista Eliminar(string Id, string Token) {
            object[] results = this.Invoke("Eliminar", new object[] {
                        Id,
                        Token});
            return ((Lista)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarAsync(string Id, string Token) {
            this.EliminarAsync(Id, Token, null);
        }
        
        /// <remarks/>
        public void EliminarAsync(string Id, string Token, object userState) {
            if ((this.EliminarOperationCompleted == null)) {
                this.EliminarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarOperationCompleted);
            }
            this.InvokeAsync("Eliminar", new object[] {
                        Id,
                        Token}, this.EliminarOperationCompleted, userState);
        }
        
        private void OnEliminarOperationCompleted(object arg) {
            if ((this.EliminarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarCompleted(this, new EliminarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarRol", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaRol EliminarRol(string Id, string Token) {
            object[] results = this.Invoke("EliminarRol", new object[] {
                        Id,
                        Token});
            return ((ListaRol)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarRolAsync(string Id, string Token) {
            this.EliminarRolAsync(Id, Token, null);
        }
        
        /// <remarks/>
        public void EliminarRolAsync(string Id, string Token, object userState) {
            if ((this.EliminarRolOperationCompleted == null)) {
                this.EliminarRolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarRolOperationCompleted);
            }
            this.InvokeAsync("EliminarRol", new object[] {
                        Id,
                        Token}, this.EliminarRolOperationCompleted, userState);
        }
        
        private void OnEliminarRolOperationCompleted(object arg) {
            if ((this.EliminarRolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarRolCompleted(this, new EliminarRolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Lista {
        
        private string respuestaField;
        
        private string mensajeField;
        
        private Modelo[] listadoField;
        
        /// <remarks/>
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Modelo[] Listado {
            get {
                return this.listadoField;
            }
            set {
                this.listadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Modelo {
        
        private string idField;
        
        private string correoField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string claveField;
        
        private string idRolField;
        
        private string estadoField;
        
        private string celularField;
        
        private string direccionField;
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        public string idRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaRol {
        
        private string respuestaField;
        
        private string mensajeField;
        
        private ModeloRol[] listadoField;
        
        /// <remarks/>
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ModeloRol[] Listado {
            get {
                return this.listadoField;
            }
            set {
                this.listadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ModeloRol {
        
        private string idField;
        
        private string tituloField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VersionCompletedEventHandler(object sender, VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaSOAPCompletedEventHandler(object sender, ConsultaSOAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaSOAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaSOAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaIdSOAPCompletedEventHandler(object sender, ConsultaIdSOAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaIdSOAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaIdSOAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaRESTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ConsultaIdRESTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LogueoCompletedEventHandler(object sender, LogueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarCompletedEventHandler(object sender, AgregarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgregarRolCompletedEventHandler(object sender, AgregarRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaRol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaRol)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarCompletedEventHandler(object sender, EditarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EditarRolCompletedEventHandler(object sender, EditarRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditarRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditarRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaRol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaRol)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarCompletedEventHandler(object sender, EliminarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Lista Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Lista)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarRolCompletedEventHandler(object sender, EliminarRolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarRolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarRolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaRol Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaRol)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591